Port to nix 0.29
ErikReider/SwayOSD pull request #109
Opened 2024-11-07 20:48 UTC by werdahias

2024-11-19 15:56 UTC, ErikReider commented
Rebase off of main

2025-01-17 16:24 UTC, werdahias commented
done.

2025-01-19 18:09 UTC, ErikReider approved these changes

2025-01-19 18:09 UTC, ErikReider requested changes
Oops, needs rebase off of main 😅

2025-01-19 20:10 UTC, werdahias commented
done

2025-01-19 20:51 UTC, ErikReider approved these changes

2025-01-19 20:51 UTC, merged