pulseaudio: fix input mute toggle
ErikReider/SwayOSD pull request #16
Opened 2023-06-07 17:33 UTC by mochaaP

2023-06-07 17:34 UTC, mochaaP commented
close #14

2023-06-09 21:35 UTC, ErikReider requested changes
Thanks for the help! :) Just one minor nit

2023-06-09 21:35 UTC, ErikReider commented on src/utils.rs
> +        }
Use tabs instead of spaces

2023-06-10 04:57 UTC, mochaaP commented on src/utils.rs
> +        }
ack

2023-06-10 09:02 UTC, ErikReider approved these changes
LGTM! Thanks again! :)

2023-06-10 09:03 UTC, merged