Add Brightness control
ErikReider/SwayOSD pull request #4
Opened 2023-02-27 22:14 UTC by p3nj

This is my first time working with rust, so if anything can be improved, please tell me.

I add a blight package to let users control the backlight.
It's tested on my laptop with multiple external screens running and worked flawlessly.
Sadly, I don't have an external monitor that can be adjusted the backlight from the drivers.
The brightness icon heavily depends on the theme files. For now, I'm using Adwaita's `display-brightness-symbolic` icon.
if desire to have different icon between different level of the brightness,
perhaps have to do something like this
```
        // in some themes they have this notification display.
        let icon_prefix = "notification-display-brightness";
        let mut icon_name = String::new();

        if brightness > 0.0 && brightness <= 82.5
        {
            icon_name = format!("{}-low", icon_prefix);
        } 
        else if brightness > 82.5 && brightness <= 165.0 {
            icon_name = format!("{}-medium", icon_prefix);
        }
        else if brightness > 165.0 {
            icon_name = format!("{}-medium", icon_prefix);
        }
```

## What changed
### General
- Update README.md file with brightness instruction
- Add parameters of brightness control
- Add function to control brightness using `blight` package.

### Package
- Added `blight = "0.4.1"`

### Issue related
#1

2023-03-07 11:41 UTC, ErikReider commented
Sorry for the delay. I'll look at this this afternoon. If I forget, ping me! :)

2023-03-07 13:40 UTC, ErikReider commented
Doesn't seem to work on my system. It failed to write to the brightness file. In the blight README, it states that the user needs to be in the video group and some udev rules may be needed

2023-03-07 15:27 UTC, ErikReider requested changes

2023-03-07 15:27 UTC, ErikReider commented on src/application.rs
> +				}
Format with rustfmt

2023-03-07 15:27 UTC, ErikReider commented on src/osd_window.rs
> +
format with rustfmt

2023-03-07 15:27 UTC, ErikReider commented on src/utils.rs
> +}
format with rustfmt

2023-03-07 15:31 UTC, ErikReider commented
Here's a patch with a few fixes:

Adds lower brightness limit, fixes progress bar not moving for some devices, and uses the Sweep animation :)

```diff
diff --git a/src/application.rs b/src/application.rs
index 3f91cf8..9f301cd 100644
--- a/src/application.rs
+++ b/src/application.rs
@@ -122,7 +122,7 @@ impl SwayOSDApplication {
 			"Shows brightness osd and raises or loweres all available sources of brightness device",
 			Some("raise|lower"),
 		);
-        
+
 		// Parse args
 		app.connect_handle_local_options(|app, args| -> i32 {
 			let variant = args.to_variant();
@@ -303,16 +303,18 @@ impl SwayOSDApplication {
 					}
 				}
 				(OsdTypes::BrightnessRaise, _) => {
-					change_brightness(BrightnessChangeType::Raise);
-                    for window in self.windows.borrow().to_owned() {
-                        window.changed_brightness();
-                    }
+					if let Ok(Some(device)) = change_brightness(BrightnessChangeType::Raise) {
+						for window in self.windows.borrow().to_owned() {
+							window.changed_brightness(&device);
+						}
+					}
 				}
 				(OsdTypes::BrightnessLower, _) => {
-					change_brightness(BrightnessChangeType::Lower);
-                    for window in self.windows.borrow().to_owned() {
-                        window.changed_brightness();
-                    }
+					if let Ok(Some(device)) = change_brightness(BrightnessChangeType::Lower) {
+						for window in self.windows.borrow().to_owned() {
+							window.changed_brightness(&device);
+						}
+					}
 				}
 				(OsdTypes::CapsLock, led) => {
 					let state = get_caps_lock_state(led);
diff --git a/src/osd_window.rs b/src/osd_window.rs
index 6e5aa0e..11e613a 100644
--- a/src/osd_window.rs
+++ b/src/osd_window.rs
@@ -156,17 +156,16 @@ impl SwayosdWindow {
 		self.run_timeout();
 	}
 
-	pub fn changed_brightness(&self) {
+	pub fn changed_brightness(&self, device: &Device) {
 		self.clear_osd();
 
-		let bl = Device::new(None).unwrap();
-        let brightness = bl.current() as f64;
-
-        // Using the icon from Adwaita for now?
-        let icon_name = "display-brightness-symbolic";
-			
+		// Using the icon from Adwaita for now?
+		let icon_name = "display-brightness-symbolic";
 		let icon = self.build_icon_widget(&icon_name);
-		let progress = self.build_progress_widget(brightness / 255.0);
+
+		let brightness = device.current() as f64;
+		let max = device.max() as f64;
+		let progress = self.build_progress_widget(brightness / max);
 
 		self.container.add(&icon);
 		self.container.add(&progress.bar);
diff --git a/src/utils.rs b/src/utils.rs
index 7184082..7f6bd1b 100644
--- a/src/utils.rs
+++ b/src/utils.rs
@@ -5,9 +5,9 @@ use std::{
 	io::{prelude::*, BufReader},
 };
 
+use blight::{change_bl, err::BlibError, Change, Device, Direction};
 use pulse::volume::Volume;
 use pulsectl::controllers::{types::DeviceInfo, DeviceControl, SinkController, SourceController};
-use blight:: { change_bl, Change, Direction };
 
 pub fn get_caps_lock_state(led: Option<String>) -> bool {
 	const BASE_PATH: &str = "/sys/class/leds";
@@ -163,22 +163,27 @@ pub fn change_source_volume(change_type: VolumeChangeType) -> Option<DeviceInfo>
 	}
 }
 
-pub fn change_brightness(change_type: BrightnessChangeType) {
-
+pub fn change_brightness(change_type: BrightnessChangeType) -> Result<Option<Device>, BlibError> {
 	const BRIGHTNESS_CHANGE_DELTA: u16 = 5;
-	match change_type {
-	BrightnessChangeType::Raise => {
-            match change_bl(BRIGHTNESS_CHANGE_DELTA, Change::Regular, Direction::Inc, None) {
-                Err(e) => eprintln!("Brightness Error: {}", e),
-                _ => ()
-            }
-		}
-	BrightnessChangeType::Lower => {
-            match change_bl(BRIGHTNESS_CHANGE_DELTA, Change::Regular, Direction::Dec, None) {
-                Err(e) => eprintln!("Brightness Error: {}", e),
-                _ => ()
+	let direction = match change_type {
+		BrightnessChangeType::Raise => Direction::Inc,
+		BrightnessChangeType::Lower => {
+			let device = Device::new(None)?;
+			let change = device.calculate_change(BRIGHTNESS_CHANGE_DELTA, Direction::Dec) as f64;
+			let max = device.max() as f64;
+			// Limits the lowest brightness to 5%
+			if change / max < (BRIGHTNESS_CHANGE_DELTA as f64) * 0.01 {
+				return Ok(Some(device));
 			}
+			Direction::Dec
+		}
+	};
+	match change_bl(BRIGHTNESS_CHANGE_DELTA, Change::Sweep, direction, None) {
+		Err(e) => {
+			eprintln!("Brightness Error: {}", e);
+			Err(e)
 		}
+		_ => Ok(Some(Device::new(None)?)),
 	}
 }
```

2023-03-07 15:37 UTC, ErikReider commented
Then you'll also need to update the README with additional instructions for setting up the permissions.

I just needed to add my user to the `video` group and the rules to `/etc/udev/rules.d/99-swayosd.rules`:

```
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
```

2023-03-07 23:50 UTC, p3nj commented
I've modified the files and the methods.
Also add a small instruction in `README.md` for adding user to `video` group.

2023-03-08 09:27 UTC, ErikReider requested changes

2023-03-08 09:27 UTC, ErikReider commented on README.md
> +Workaround will be adding a rule inside `udev`:
Also mention the command to add the user to video group :)

2023-03-08 11:26 UTC, p3nj commented
> GTK requires the adwaita icons to be installed so that icon should work :)
> 
> Too bad that they don't provide more brightness icons...

Sorry, forgot to commit the change.

Some of the themes have multiple icons available, probably could replace it with Font Emoji or something else?

2023-03-08 11:27 UTC, ErikReider approved these changes
LGTM! Appreciate the help! :)

2023-03-08 11:28 UTC, merged

2023-03-08 12:07 UTC, ErikReider commented
> Some of the themes have multiple icons available, probably could replace it with Font Emoji or something else?

I'd prefer using icons. The one used right now works good enough :)