Fix bug related to blight and add a feature for brightness
ErikReider/SwayOSD pull request #67
Opened 2023-12-15 21:13 UTC by Albert24GG

When using this program I noticed that when changing brightness quickly(ex: raise it two times and then lower it), the indicator(osd bar) would not reflect this changes(in case of the previous example it would raise when I lower the brightness). So I found out that the current brightness of the blight does not update properly. Reloading the device current value solved this issue.
Another problem I found is that there was no way to change the brightness by a custom delta anymore(this was possible before), so I added some code that checks if the argument is signed or not and applies the changes(if not signed, then that means user wants to set the value to that value).

2024-02-22 15:36 UTC, Albert24GG commented
@ErikReider Hey, did you have time to look over this PR? Is there any changes I have to make? Thanks!

2024-03-25 22:43 UTC, ErikReider requested changes
Otherwise LGTM :)

2024-03-25 22:43 UTC, ErikReider commented on src/global_utils.rs
> +				};
Something like this would be better:

```rust
let coef: i32 = match value.get(..1) {
	Some("1") => 1,
	Some("-1") => -1,
	_ => 0,
};
```

2024-03-26 13:07 UTC, Albert24GG commented on src/global_utils.rs
> +				};
Done!

2024-04-15 21:20 UTC, ErikReider approved these changes
Thanks! :)

2024-04-15 21:20 UTC, merged