Add percentage labels to volume and brightness indicators
ErikReider/SwayOSD pull request #69
Opened 2023-12-24 22:31 UTC by Ferdi265

This PR adds a textual percentage next to the progress bar in the volume and brightness indicators. This is useful for users who still want to know the exact volume percentage set in practice.

Optimally this should be configurable, but this PR currently just unconditionally adds these percentage indicators. I will potentially add configurability if I find time.

2024-02-12 21:13 UTC, ErikReider requested changes
I'd also prefer if the user could disable this. Might wait with this until config support has been added to undo some of the cmdline arg clutter

2024-02-12 21:13 UTC, ErikReider commented on src/server/osd_window.rs
> +		label.set_text(&format!("{}%", (brightness / max * 100.) as i32));
Pass the formatted string to `build_text_widget` instead of setting the text manually

2024-02-12 21:54 UTC, Ferdi265 commented on src/server/osd_window.rs
> +		label.set_text(&format!("{}%", (brightness / max * 100.) as i32));
Fixed in 9e12cd5.

I haven't written a lot of Rust lately, so I don't know if there's a better way to wrap the `&str` in an `Option` than to manually construct the `Some()`, but this should do for now.

2024-02-12 21:55 UTC, Ferdi265 commented
> I'd also prefer if the user could disable this. Might wait with this until config support has been added to undo some of the cmdline arg clutter

Yes, that is my thought as well. I'm completely fine with leaving this PR hanging until config support is added, I might even help with implementing config support if I find time.

2024-02-18 14:21 UTC, Ferdi265 commented
Rebased on top of #79 and added a configuration option to enable percentage display.

2024-03-25 22:46 UTC, ErikReider commented
I'll wait until #79 is merged :)

2024-08-25 15:24 UTC, Ferdi265 commented
rebased onto the merged config branch

2024-09-08 11:38 UTC, rubiin commented
@ErikReider I think this can be merged

2024-09-08 11:56 UTC, Ferdi265 commented
@ErikReider if you'd like to reduce the number of things in the CLI options I can also remove the CLI option added in this PR (I already have a fixup commit for that locally, I'd just need to push it)

2024-09-11 17:34 UTC, ErikReider commented
> @ErikReider if you'd like to reduce the number of things in the CLI options I can also remove the CLI option added in this PR (I already have a fixup commit for that locally, I'd just need to push it)

That would be appreciated! :D

2024-09-11 19:25 UTC, Ferdi265 commented
> > @ErikReider if you'd like to reduce the number of things in the CLI options I can also remove the CLI option added in this PR (I already have a fixup commit for that locally, I'd just need to push it)
> 
> That would be appreciated! :D

done

2024-09-11 19:27 UTC, ErikReider approved these changes
Thanks for your patience! :)

2024-09-11 19:27 UTC, merged