Add support for custom messages with icons
ErikReider/SwayOSD pull request #97
Opened 2024-09-01 17:57 UTC by 3akev

This PR adds support for displaying arbitrary text messages and icons, which opens up the possible use cases immensely. For example, I use this to display a message when I change my keyboard layout.

![Untitled](https://github.com/user-attachments/assets/77322e41-cb19-47c0-be9c-dfb0e1071882)

This is done by adding two CLI options, `--custom-message` and `--custom-icon`.

2024-09-05 14:46 UTC, rubiin approved these changes

2024-09-11 17:16 UTC, ErikReider requested changes
Other wise, LGTM! :)

2024-09-11 17:16 UTC, ErikReider commented on src/server/osd_window.rs
> +		}
Currently, the text becomes off centered when there's an icon. Adding a right margin to the text with the size of the icon would center it (only if the icon is visible)

2024-09-11 19:48 UTC, ErikReider approved these changes
LGTM! :)

2024-09-11 19:48 UTC, merged